import { type NextPage } from 'next';
import Head from 'next/head';
import { signIn, signOut, useSession } from 'next-auth/react';
import { Header } from '../components/Header';

import { api } from '~/utils/api';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Notetaker</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Header />
				<Content />
			</main>
		</>
	);
};

export default Home;

const Content: React.FC = () => {
	const { data: sessionData } = useSession();

	const { data: topics, refetch: refetchTopics } = api.topic.getAll.useQuery(
		undefined, //no input
		{
			enabled: sessionData?.user !== undefined,
		}
	);

	const create_topic = api.topic.create.useMutation({});

	return (
		<div className='mx-5 mt-5 grid grid-cols-4 gap-2'>
			<div className='px-2'></div>
			<div className='col-span-3'></div>

		</div>
	);
};
